Repository pmem/kvdk, pull requests merged in 2022-05, with the labels that each got.

#261 Fix segfault when popping an empty list
  engine/kv_engine.cpp
  tests/tests.cpp
Labels: bug-fix

#262 Fix latency calculation in benchmark
  benchmark/bench.cpp
Labels: bug-fix

#259 Purge delete record of skiplist in recovery
  engine/sorted_collection/rebuilder.cpp
  engine/sorted_collection/rebuilder.hpp
Labels: bug-fix

#260 Add destroy sorted collection C API
  engine/c.cpp
  examples/tutorial/c_api_tutorial.c
  include/kvdk/engine.h
Labels: new-feature

#265 Fix snapshot of sorted iterator
  engine/kv_engine_sorted.cpp
Labels: bug-fix

#263 Hash/List Create() and Destroy() API
  engine/c.cpp
  engine/c/kvdk_hash.cpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_hash.cpp
  examples/tutorial/c_api_tutorial.c
  examples/tutorial/cpp_api_tutorial.cpp
  include/kvdk/engine.h
  include/kvdk/engine.hpp
  include/kvdk/status.h
  tests/c_api_test_hash.cpp
  tests/c_api_test_list.cpp
  tests/stress_test.cpp
  tests/tests.cpp
Labels: new-feature

#266 Hash table refactor
  CMakeLists.txt
  engine/c.cpp
  engine/dram_allocator.hpp
  engine/hash_table.cpp
  engine/hash_table.hpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_hash.cpp
  engine/kv_engine_sorted.cpp
  engine/kv_engine_string.cpp
  engine/sorted_collection/rebuilder.cpp
  engine/sorted_collection/skiplist.cpp
  examples/tutorial/c_api_tutorial.c
  examples/tutorial/zset.c
  include/kvdk/configs.hpp
  include/kvdk/engine.h
  tests/c_api_test.hpp
  tests/stress_test.cpp
  tests/tests.cpp
Labels: refactor

#269 Bug fix: Sorted collection size
  engine/sorted_collection/rebuilder.cpp
  engine/sorted_collection/skiplist.cpp
Labels: bug-fix

#272 Bugfix: replace header of a empty skiplist
  engine/sorted_collection/rebuilder.cpp
  engine/sorted_collection/skiplist.cpp
  tests/tests.cpp
Labels: bug-fix

#273 Fix checkpoint recovery of skiplist
  engine/sorted_collection/rebuilder.cpp
Labels: bug-fix

#271 fix expire API: remove ttl_time <=0 check.
  engine/kv_engine_string.cpp
  examples/tutorial/c_api_tutorial.c
  examples/tutorial/cpp_api_tutorial.cpp
  include/kvdk/configs.hpp
  tests/tests.cpp
Labels: bug-fix

#270 API Rename
  benchmark/bench.cpp
  doc/user_doc.md
  engine/c.cpp
  engine/c/kvdk_hash.cpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_hash.cpp
  engine/kv_engine_sorted.cpp
  engine/kv_engine_string.cpp
  engine/sorted_collection/skiplist.cpp
  engine/sorted_collection/skiplist.hpp
  examples/graph_sim/src/graph_impl.cpp
  examples/graph_sim/src/kv_engines/kvdk.cpp
  examples/kvredis/0001-redis-with-kvdk.patch
  examples/kvrocks/0001-use-KVDK-for-set-get-operations.patch
  examples/tutorial/c_api_tutorial.c
  examples/tutorial/cpp_api_tutorial.cpp
  examples/tutorial/zset.c
  include/kvdk/engine.h
  include/kvdk/engine.hpp
  tests/c_api_test_hash.cpp
  tests/c_api_test_list.cpp
  tests/stress_test.cpp
  tests/tests.cpp
Labels: refactor

#268 Batch Write API for collections and String
  CMakeLists.txt
  benchmark/bench.cpp
  engine/c.cpp
  engine/c/kvdk_batch.cpp
  engine/c/kvdk_c.hpp
  engine/data_record.hpp
  engine/hash_table.hpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_hash.cpp
  engine/kv_engine_sorted.cpp
  engine/kv_engine_string.cpp
  engine/utils/codec.hpp
  engine/utils/sync_impl.hpp
  engine/utils/sync_point.cpp
  engine/utils/sync_point.hpp
  engine/utils/test.cpp
  engine/version/version_controller.hpp
  engine/write_batch.cpp
  engine/write_batch_impl.cpp
  engine/write_batch_impl.hpp
  examples/tutorial/c_api_tutorial.c
  examples/tutorial/cpp_api_tutorial.cpp
  include/kvdk/engine.h
  include/kvdk/engine.hpp
  include/kvdk/status.h
  include/kvdk/write_batch.hpp
  tests/tests.cpp
Labels: refactor, new-feature

#276 Resolve compiler warning
  engine/kv_engine.cpp
Labels: bug-fix

#279 Check linkage before unlink or replace a skiplist record
  engine/kv_engine_sorted.cpp
  engine/sorted_collection/rebuilder.cpp
  engine/sorted_collection/skiplist.cpp
  engine/sorted_collection/skiplist.hpp
  engine/version/old_records_cleaner.cpp
Labels: refactor

#282 Batchwrite test case fix
  CMakeLists.txt
  engine/kv_engine.cpp
  engine/sorted_collection/rebuilder.cpp
  engine/utils/sync_impl.hpp
  engine/utils/sync_point.hpp
  engine/write_batch_impl.cpp
  engine/write_batch_impl.hpp
  tests/tests.cpp
Labels: bug-fix

#284 Fix benchmark
  benchmark/bench.cpp
  include/kvdk/status.h
Labels: bug-fix

#280 Fix test cases with sync points
  engine/utils/sync_impl.hpp
  tests/tests.cpp
Labels: bug-fix

#285 Prevent duplicate key from WriteBatch
  engine/kv_engine.cpp
  engine/utils/utils.hpp
  engine/write_batch_impl.hpp
  include/kvdk/write_batch.hpp
  tests/tests.cpp
Labels: bug-fix

#289 Bug fix: skiplist destroy
  engine/sorted_collection/skiplist.cpp
Labels: bug-fix

#283 Implement BatchWrite for Hash
  CMakeLists.txt
  benchmark/bench.cpp
  engine/generic_list.hpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_hash.cpp
  engine/write_batch_impl.cpp
  engine/write_batch_impl.hpp
  scripts/benchmark_impl.py
  tests/tests.cpp
Labels: new-feature

#287 Implement batch write for sorted collections
  benchmark/bench.cpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_sorted.cpp
  engine/kv_engine_string.cpp
  engine/sorted_collection/skiplist.cpp
  engine/sorted_collection/skiplist.hpp
  engine/write_batch_impl.hpp
  scripts/benchmark_impl.py
  tests/tests.cpp
Labels: new-feature

#288 Add regular expression interface for hash iterator
  engine/c.cpp
  engine/c/kvdk_c.hpp
  engine/c/kvdk_hash.cpp
  engine/hash_list.hpp
  include/kvdk/engine.h
  include/kvdk/iterator.hpp
  tests/c_api_test_hash.cpp
  tests/tests.cpp
Labels: new-feature

#290 Chaining old versions of List and HashSet
  engine/generic_list.hpp
  engine/kv_engine.cpp
  engine/kv_engine_hash.cpp
  tests/tests.cpp
Labels: bug-fix
