Repository pmem/kvdk, pull requests merged in 2022-06, with the labels that each got.

#277 Background Cleaner Refactor
  CMakeLists.txt
  engine/alias.hpp
  engine/data_record.hpp
  engine/generic_list.hpp
  engine/hash_table.cpp
  engine/hash_table.hpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_cleaner.cpp
  engine/kv_engine_hash.cpp
  engine/kv_engine_sorted.cpp
  engine/kv_engine_string.cpp
  engine/pmem_allocator/free_list.cpp
  engine/sorted_collection/iterator.hpp
  engine/sorted_collection/rebuilder.cpp
  engine/sorted_collection/skiplist.cpp
  engine/sorted_collection/skiplist.hpp
  engine/version/old_records_cleaner.cpp
  engine/version/old_records_cleaner.hpp
  include/kvdk/configs.hpp
  tests/stress_test.cpp
  tests/tests.cpp
Labels: refactor

#294 Fix skiplist get
  engine/sorted_collection/skiplist.cpp
Labels: bug-fix

#293 Add TypeOf() API
  engine/backup_log.hpp
  engine/c.cpp
  engine/c/kvdk_c.hpp
  engine/collection.hpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  include/kvdk/engine.h
  include/kvdk/engine.hpp
  include/kvdk/status.h
  include/kvdk/status.hpp
  include/kvdk/types.h
  include/kvdk/types.hpp
  tests/tests.cpp
Labels: new-feature

#292 Return Status when creating an iterator for error reporting
  engine/c.cpp
  engine/c/kvdk_hash.cpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_hash.cpp
  engine/kv_engine_sorted.cpp
  examples/tutorial/c_api_tutorial.c
  examples/tutorial/zset.c
  include/kvdk/engine.h
  include/kvdk/engine.hpp
  tests/c_api_test_hash.cpp
  tests/c_api_test_list.cpp
Labels: new-feature

#296 Fix old version reset in sorted collection recovery
  engine/kv_engine_cleaner.cpp
  engine/sorted_collection/rebuilder.cpp
  engine/sorted_collection/skiplist.cpp
Labels: bug-fix

#299 Fix no-hash-indexed sorted collection clean
  engine/kv_engine.hpp
  engine/kv_engine_cleaner.cpp
  engine/sorted_collection/skiplist.cpp
  engine/sorted_collection/skiplist.hpp
Labels: bug-fix

#298 Classified large free space entry with thread cache in pmem allocator
  engine/allocator.hpp
  engine/pmem_allocator/free_list.cpp
  engine/pmem_allocator/free_list.hpp
Labels: new-feature

#297 Add Foreground cached outdated records
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_cleaner.cpp
  engine/kv_engine_sorted.cpp
  engine/kv_engine_string.cpp
  engine/version/old_records_cleaner.cpp
  engine/version/version_controller.hpp
Labels: new-feature

#295 Move functions to separate files
  CMakeLists.txt
  engine/c.cpp
  engine/c/kvdk_basic_op.cpp
  engine/c/kvdk_batch.cpp
  engine/c/kvdk_c.hpp
  engine/c/kvdk_hash.cpp
  engine/c/kvdk_list.cpp
  engine/c/kvdk_sorted.cpp
  engine/c/kvdk_string.cpp
  engine/kv_engine.cpp
  engine/kv_engine_list.cpp
Labels: refactor

#304 Pause longer in TTS spinlock to optimize performance.
  engine/utils/utils.hpp
Labels: performance-optimize

#305 Fix List and Hash Iterator Behavior
  engine/hash_list.hpp
  engine/simple_list.hpp
Labels: bug-fix

#307 Split RecordType to type and status
  engine/data_record.cpp
  engine/data_record.hpp
  engine/generic_list.hpp
  engine/hash_table.cpp
  engine/hash_table.hpp
  engine/kv_engine.cpp
  engine/kv_engine.hpp
  engine/kv_engine_cleaner.cpp
  engine/kv_engine_hash.cpp
  engine/kv_engine_list.cpp
  engine/kv_engine_sorted.cpp
  engine/kv_engine_string.cpp
  engine/pmem_allocator/pmem_allocator.cpp
  engine/sorted_collection/iterator.hpp
  engine/sorted_collection/rebuilder.cpp
  engine/sorted_collection/skiplist.cpp
  engine/sorted_collection/skiplist.hpp
  engine/version/old_records_cleaner.cpp
Labels: refactor
